name: "Build Resume (PDF)"
on:
  push:
    branches:
        - main
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - run: nix build .#pdf
    - uses: actions/upload-artifact@v4
      with:
        path: "result/resume.pdf"
